### ISSUE TITLE
Activities that flip privacy do not (re)post

### ISSUE THREAD

**Issue by dmitry-mukhin** [dblock/slack-strava#95] opened 2020-06-25 08:15 UTC
I've connected Slava with all the permissions and turned off "private" activities in the bot settings.

My Strava activities are private by default and I mark some of them to be visible to "followers". However, those marked activities are not being fetched by the bot.
Are "followers" activities considered to be private as well or is there some more granular approach to this?

**Comment by dblock** [comment] 2020-06-25 13:22
This is what I'm seeing [in Strava data](https://github.com/dblock/slack-strava/blob/adbb3716a1317ee0cf092edb7acdfd7b6845eb97/spec/fixtures/strava/user_sync_new_strava_activities_privacy.yml#L63):

- "private":false,"visibility":"everyone"
- "private":true,"visibility":"only_me"
- "private":false,"visibility":"followers_only"

The last one is telling me that followers only activities are not private, so they should get posted regardless of what the private setting is. Could you please give me an activity ID (the URL on Strava is good enough) so I can take a look at the data?

I also added more granular controls for followers only activities in https://github.com/dblock/slack-strava/commit/adbb3716a1317ee0cf092edb7acdfd7b6845eb97, so you can toggle whether you want to see these with `set followers true` or `set followers false`.

**Comment by dmitry-mukhin** [comment] 2020-06-25 14:23
the latest one is 3665843955
thanks

**Comment by dblock** [comment] 2020-06-25 23:28
This is what I am seeing.

1. activity was first noticed on 2020-06-24T19:57:00, but it was private and therefore not posted to Slack
1. activity changed title on 2020-06-24T20:00:03
1. activity privacy was changed on 2020-06-24T20:04:58 to private=false
1. activity privacy was changed back to true on 2020-06-25T15:21:43

The issue is just that privacy change on the activity doesn't re-trigger a post. The first time the activity was synced, it was skipped and marked as processed.

I guess this could be treated as a non-feature - if the activity switches privacy settings, it could be posted. Not sure whether it's worth fixing.

**Comment by dmitry-mukhin** [comment] 2020-06-26 05:53
I see.

4. and later I was playing with the setting to see if it would trigger a sync on Slava's side.

The problem (for me) is that my activities are uploaded automatically from various devices and private by default and I will not  change that :)

**Comment by dblock** [comment] 2020-06-26 13:47
I tried implementing this in https://github.com/dblock/slack-strava/commit/620d594957b35ab6bc0bbf4faaccaf6ec5cbc978 and https://github.com/dblock/slack-strava/commit/93d672a8c542c52d756b9fa0f59e2a159099a4ce. Let me know if this works for you?

**Closed by dblock** 2020-06-26 13:47 UTC
Labels: confirmed bug, new feature

**Comment by dmitry-mukhin** [comment] 2020-06-29 09:49
Yes, rebragging started.
Thanks
